[[mpif]]
arch = "aarch64"
git-tree-sha1 = "12af220d7c5fb115ab29d1c110294bc67489f119"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[mpif.download]]
    sha256 = "6d5cbd9a35693be4569fdf1c026ddbffb46d8cc6c59c6ee78a439fdd2e74ffef"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "aarch64"
git-tree-sha1 = "82f366ed1322f09e2b328ac98c2c706d240055be"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "62ef1168b30f4bbda4c937126395bd4a72bd4c107a6d9bc049d56ff965aa9d58"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "aarch64"
git-tree-sha1 = "ab02f143089de6fdb24eee4c332efaa900e87849"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "804ea6f0c2c764e932bb1b689c930ce313f3d5e20f164e5803763c95e8d0030d"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "aarch64"
git-tree-sha1 = "9dd778d3728cafb1f4e09a444dbfe6f695dc6f5a"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[mpif.download]]
    sha256 = "279f1333b5b3b3df2effd99c6dcd263869d70ac8e1cbb786626581e02164821e"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "814275b5e9789ad7c136eba84b7336a24377e78f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "ad9f5c05acc8519f19eea1b95b9af1f1d6a30b028cd7552272191ddee993423e"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.armv6l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f21fa01844728b1c53c612ae448752e17940f3fd"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "dccbc7f26e03b6016ef04ae534f6589c1759e66fde9d359e64dfa91212364e7b"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.armv6l-linux-musleabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7b60b10e2a4987aaf5ab9f17e311994d768d937"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "fa965b6b3a9d22b55b2e72332cb16ff62240643600573731bce75578c1e0edde"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.armv7l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "237481ffb8837414c8d3646ed88a6107b76566d6"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "5862fe243e981008d0670386dc131cc045080e1f0899f6e48c8eb312c604b65f"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.armv7l-linux-musleabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "i686"
git-tree-sha1 = "eb02d0419d00346586007058063a29723e657485"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "8dcf64bfa13a7842a7a71efc854394cff466e80630bb68369443275b0be60720"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "i686"
git-tree-sha1 = "0322d392191131e35804157f34ba5ba50a920d94"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "f2e8575a395e3327097f1531f4e13666a65e10693576b40c0dbec90eb1b27b29"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.i686-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "powerpc64le"
git-tree-sha1 = "6edfd9a240a4b8a33a4e6153baffbc60b7d396da"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "8c2cdbb40dee313b5a0f83dc4866aa6cb47bd0ce99c0e7e8393ac19cd6d8cbec"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "riscv64"
git-tree-sha1 = "9513b19c69f749fbb4787d2d14679c96e0d5425a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "3692d8f4e8f659035cee003e34454c9c6700c86dd6a451d252bb06f9c95543ee"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "x86_64"
git-tree-sha1 = "5bda6747d8438e4fcd372de505cba2d8f3dcbf38"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[mpif.download]]
    sha256 = "05fba8b10f77a689c96e51bf713d7412356e0e5eaae24dfde95572d324bb2e4b"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "x86_64"
git-tree-sha1 = "e3259a7dba6e97f1c12390cf8b9f5b0a27b7ff6c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "968245ae21c749e54a7f33bf76f969dc4bd27ddcdd69be48a838d2b417c5b22c"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "x86_64"
git-tree-sha1 = "9a6241608f9b8d6878fa3f7608849c9e2f1a462a"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[mpif.download]]
    sha256 = "d5d79711ccadaeb9d5d7e0a295215dd66b2ae502f68ccfef600630def343d254"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[mpif]]
arch = "x86_64"
git-tree-sha1 = "350befcfdd205f80932e52235dcc709e246ae39d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[mpif.download]]
    sha256 = "39c7101e3ba6691de4dc069f6ae54b7f7974338bef17bac6ce4dff09d2f47c1b"
    url = "https://github.com/JuliaBinaryWrappers/mpif_jll.jl/releases/download/mpif-v0.1.5+0/mpif.v0.1.5.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
