# Autogenerated wrapper script for mpif_jll for aarch64-apple-darwin-libgfortran5-mpi+mpiabi
export libmpif

using CompilerSupportLibraries_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("mpif")
JLLWrappers.@declare_library_product(libmpif, "@rpath/libmpif.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libmpif,
        "lib/libmpif.0.1.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
