# Autogenerated wrapper script for mpif_jll for aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi
export libmpif

using CompilerSupportLibraries_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("mpif")
JLLWrappers.@declare_library_product(libmpif, "libmpif.so.0")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libmpif,
        "lib/libmpif.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
